/*
* ==================================================================================
* File:             CPartCatalogServiceGroup.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import java.rmi.*;
import javax.ejb.*;

/** 
 * Home interface for the <code>CPartCatalogServiceGroup</code> Activity Group.
 */
public interface CPartCatalogServiceGroupHome extends EJBHome {
   CPartCatalogServiceGroupRemote create()  throws RemoteException, CreateException ;
}
