/*
* ==================================================================================
* File:             CPartCatalogService.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.record.*;
import javax.ejb.EJBLocalObject;

/**
 * Interface for the <code>CPartCatalogService</code> handler.
 */
public interface CPartCatalogService extends EJBLocalObject {
   /**
    * <p><b>Remarks:</b>
    * @param CPartCatalogRequestArray PartCatalogRequest
    * @return CPartCatalogResponseArray
    * @throws IfsException
    */
   public CPartCatalogResponseArray cCreatePartCatalog(CPartCatalogRequestArray partCatalogRequest) throws IfsException;

   public interface Operations   {

      /**
       * <p><b>Remarks:</b>
       * @param CPartCatalogRequestArray PartCatalogRequest
       * @return CPartCatalogResponseArray
       * @throws IfsException
       */
      public CPartCatalogResponseArray cCreatePartCatalog(CPartCatalogRequestArray partCatalogRequest) throws IfsException;
   }
}