/*
* ==================================================================================
* File:             CPartCatalogServiceHome.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/


package ifs.application.cpartcatalogservicegroup;

import javax.ejb.EJBLocalHome;
import javax.ejb.CreateException;

/**
 * Home interface for the <code>CPartCatalogService</code> handler
*/
public interface CPartCatalogServiceHome extends EJBLocalHome {
   CPartCatalogService create() throws CreateException;
}