/*
* ==================================================================================
* File:             CPartCatalogPlsqlAPIImplBase.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.sf.*;
import ifs.fnd.sf.storage.*;
import ifs.fnd.record.*;
import ifs.fnd.sf.storage.FndAbstractHandler;
import ifs.fnd.sf.storage.FndPlsqlAccess;
import ifs.fnd.services.plsqlserver.AttributeString;

/**
 * Base implementation of the <code>CPartCatalogPlsqlAPI</code> handler.
 */
public abstract class CPartCatalogPlsqlAPIImplBase extends FndAbstractHandler implements CPartCatalogPlsqlAPI.Operations {

   protected final FndPlsqlAccess plsqlAccess = new FndPlsqlAccess();

   private static final String stmt_CREATEPARTCATALOG0  = 
      "BEGIN &AO.C_PART_CATALOG_API.CREATE_PART_CATALOG (" + 
         ":PART_NO_," + 
         ":DESCRIPTION_," + 
         ":UNIT_CODE_);" +
      "END;";

   /**
    * <p><b>Remarks:</b>
    * @param FndText part_no_
    * @param FndText description_
    * @param FndText unit_code_
    * @return void
    * @throws IfsException
    */
   protected void plsqlCreatePartCatalog(final FndText part_no_, final FndText description_, final FndText unit_code_) throws IfsException {
      //Create bind variables
      FndRecord params = new FndRecord();
      params.add("PART_NO_", (part_no_ != null) ? part_no_ : new FndText(), "IN");
      params.add("DESCRIPTION_", (description_ != null) ? description_ : new FndText(), "IN");
      params.add("UNIT_CODE_", (unit_code_ != null) ? unit_code_ : new FndText(), "IN");
      //Execute the PL/SQL method
      plsqlAccess.execute(stmt_CREATEPARTCATALOG0, params);
      //Return data to caller
   }
}
