/*
* ==================================================================================
* File:             CPartCatalogRequestArray.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import ifs.fnd.record.*;
import ifs.fnd.record.serialization.*;
import ifs.fnd.base.*;

/** 
 * Array of <code>CPartCatalogRequest</code>.
 */
public class CPartCatalogRequestArray extends FndAbstractArray {

   public CPartCatalogRequestArray() {
      super();
   }

   public CPartCatalogRequestArray(FndAttributeMeta meta) {
      super(meta);
   }

   public CPartCatalogRequestArray(FndAttributeMeta meta, FndCompoundReference parentKeyInParent) {
      super(meta, parentKeyInParent);
   }

   public boolean add(CPartCatalogRequest record) {
      return internalAdd(record);
   }

   public void add(int index, CPartCatalogRequest record) {
      internalAdd(index, record);
   }

   public void add(CPartCatalogRequestArray array) {
      internalAdd(array);
   }

   public void assign(CPartCatalogRequestArray from) throws SystemException {
      assign(from, true);
   }

   public boolean contains(CPartCatalogRequest record) {
      return internalContains(record);
   }

   public boolean equals(CPartCatalogRequest record) {
      return internalEquals(record);
   }

   public CPartCatalogRequest firstElement() {
      return (CPartCatalogRequest)internalFirstElement();
   }

   public CPartCatalogRequest get(int index) {
      return (CPartCatalogRequest)internalGet(index);
   }

   public int indexOf(CPartCatalogRequest record) {
      return internalIndexOf(record);
   }

   public CPartCatalogRequest lastElement() {
      return (CPartCatalogRequest)internalLastElement();
   }

   public int lastIndexOf(CPartCatalogRequest record) {
      return internalLastIndexOf(record);
   }

   public CPartCatalogRequest remove(int index) {
      return (CPartCatalogRequest)internalRemove(index);
   }

   public CPartCatalogRequest set(int index, CPartCatalogRequest record) {
      return (CPartCatalogRequest)internalSet(index, record);
   }

   public FndAbstractRecord newRecord() {
      return new CPartCatalogRequest();
   }

   protected FndAbstractRecord newRecord(FndTokenReader stream) throws ParseException {
      CPartCatalogRequest record = new CPartCatalogRequest();
      record.parse(stream);
      return record;
   } 

   protected FndAttribute newAttribute(FndAttributeMeta meta) {
       return new CPartCatalogRequestArray(meta);
   }
}
