/*
* ==================================================================================
* File:             CPartCatalogResponse.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import ifs.fnd.record.*;
import ifs.fnd.base.*;

/**
 * This view represents the <code>CPartCatalogResponse</code> entity.
 */
public class CPartCatalogResponse extends FndView {

   public static final FndRecordMeta viewMeta  = new FndRecordMeta("CPARTCATALOGSERVICEGROUP", "C_PART_CATALOG_RESPONSE").setViewClassName("ifs.application.cpartcatalogservicegroup.CPartCatalogResponse");

   /**
    * PartNo
    */
   public final FndText      partNo        = new FndText(Meta.partNo);
   /**
    * StatusCode
    */
   public final FndText      statusCode    = new FndText(Meta.statusCode);
   /**
    * ReturnMessage
    */
   public final FndText      returnMessage = new FndText(Meta.returnMessage);

   public CPartCatalogResponse() {
      this(viewMeta);
   }

   protected CPartCatalogResponse(FndRecordMeta meta) {
      super(meta);
      add(partNo);
      add(statusCode);
      add(returnMessage);
   }

   public void assign(CPartCatalogResponse from) throws SystemException {
      super.assign(from);
   }

   public FndAbstractRecord newInstance() {
      return new CPartCatalogResponse();
   }

   public FndAbstractArray newArrayInstance() {
      return new CPartCatalogResponseArray();
   }

   public void transformTo(final CPartCatalogResponse to) throws SystemException {
      transformView(to);
   }

   public static class Meta {
      public static final FndAttributeMeta partNo          = new FndAttributeMeta(viewMeta, "PART_NO", "", 0, 25);
      public static final FndAttributeMeta statusCode      = new FndAttributeMeta(viewMeta, "STATUS_CODE", "", 0, 20);
      public static final FndAttributeMeta returnMessage   = new FndAttributeMeta(viewMeta, "RETURN_MESSAGE", "", 0, 2000);
   }
}
