/*
* ==================================================================================
* File:             CPartCatalogPlsqlAPI.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.record.*;
import javax.ejb.EJBLocalObject;

/**
 * Interface for the <code>CPartCatalogPlsqlAPI</code> handler.
 */
public interface CPartCatalogPlsqlAPI extends EJBLocalObject {
   /**
    * <p><b>Remarks:</b>
    * @param String PartNo
    * @param String Description
    * @param String UnitCode
    * @return void
    * @throws IfsException
    */
   public void createPartCatalog(String partNo, String description, String unitCode) throws IfsException;

   public interface Operations   {

      /**
       * <p><b>Remarks:</b>
       * @param String PartNo
       * @param String Description
       * @param String UnitCode
       * @return void
       * @throws IfsException
       */
      public void createPartCatalog(String partNo, String description, String unitCode) throws IfsException;
   }
}