/*
* ==================================================================================
* File:             CPartCatalogRequest.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import ifs.fnd.record.*;
import ifs.fnd.base.*;

/**
 * This view represents the <code>CPartCatalogRequest</code> entity.
 */
public class CPartCatalogRequest extends FndView {

   public static final FndRecordMeta viewMeta  = new FndRecordMeta("CPARTCATALOGSERVICEGROUP", "C_PART_CATALOG_REQUEST").setViewClassName("ifs.application.cpartcatalogservicegroup.CPartCatalogRequest");

   /**
    * PartNo
    */
   public final FndText      partNo      = new FndText(Meta.partNo);
   /**
    * Description
    */
   public final FndText      description = new FndText(Meta.description);
   /**
    * UnitCode
    */
   public final FndText      unitCode    = new FndText(Meta.unitCode);

   public CPartCatalogRequest() {
      this(viewMeta);
   }

   protected CPartCatalogRequest(FndRecordMeta meta) {
      super(meta);
      add(partNo);
      add(description);
      add(unitCode);
   }

   public void assign(CPartCatalogRequest from) throws SystemException {
      super.assign(from);
   }

   public FndAbstractRecord newInstance() {
      return new CPartCatalogRequest();
   }

   public FndAbstractArray newArrayInstance() {
      return new CPartCatalogRequestArray();
   }

   public void transformTo(final CPartCatalogRequest to) throws SystemException {
      transformView(to);
   }

   public static class Meta {
      public static final FndAttributeMeta partNo          = new FndAttributeMeta(viewMeta, "PART_NO", "", 0, 25);
      public static final FndAttributeMeta description     = new FndAttributeMeta(viewMeta, "DESCRIPTION", "", 0, 200);
      public static final FndAttributeMeta unitCode        = new FndAttributeMeta(viewMeta, "UNIT_CODE", "", 0, 30);
   }
}
