/*
* ==================================================================================
* File:             CPartCatalogServiceWrapper.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.record.*;
import ifs.fnd.sf.*;
import ifs.fnd.sf.storage.*;
import ifs.application.cpartcatalogservicegroup.impl.CPartCatalogServiceImpl;

/**
 * Handler implementation wrapper instantitated by <code>CPartCatalogServiceFactory</code>.
 */
class CPartCatalogServiceWrapper extends CPartCatalogServiceImpl {

   protected CPartCatalogServiceWrapper() {
      setActivityName("CPartCatalogService");
   }

   /**
    * <p><b>Remarks:</b>
    * @param CPartCatalogRequestArray PartCatalogRequest
    * @return CPartCatalogResponseArray
    * @throws IfsException
    */
   public CPartCatalogResponseArray cCreatePartCatalog(CPartCatalogRequestArray partCatalogRequest) throws IfsException {
      beforeCall("cCreatePartCatalog");
      try {
         return super.cCreatePartCatalog(partCatalogRequest);
      }
      finally {
         afterCall();
      }
   }
}
