/*
* ==================================================================================
* File:             CPartCatalogPlsqlAPIWrapper.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.record.*;
import ifs.fnd.sf.*;
import ifs.fnd.sf.storage.*;
import ifs.application.cpartcatalogservicegroup.impl.CPartCatalogPlsqlAPIImpl;

/**
 * Handler implementation wrapper instantitated by <code>CPartCatalogPlsqlAPIFactory</code>.
 */
class CPartCatalogPlsqlAPIWrapper extends CPartCatalogPlsqlAPIImpl {

   protected CPartCatalogPlsqlAPIWrapper() {
      setActivityName(null);
   }

   /**
    * <p><b>Remarks:</b>
    * @param String PartNo
    * @param String Description
    * @param String UnitCode
    * @return void
    * @throws IfsException
    */
   public void createPartCatalog(String partNo, String description, String unitCode) throws IfsException {
      beforeCall("createPartCatalog");
      try {
         super.createPartCatalog(partNo, description, unitCode);
      }
      finally {
         afterCall();
      }
   }
}
