/*
* ==================================================================================
* File:             CPartCatalogResponseArray.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import ifs.fnd.record.*;
import ifs.fnd.record.serialization.*;
import ifs.fnd.base.*;

/** 
 * Array of <code>CPartCatalogResponse</code>.
 */
public class CPartCatalogResponseArray extends FndAbstractArray {

   public CPartCatalogResponseArray() {
      super();
   }

   public CPartCatalogResponseArray(FndAttributeMeta meta) {
      super(meta);
   }

   public CPartCatalogResponseArray(FndAttributeMeta meta, FndCompoundReference parentKeyInParent) {
      super(meta, parentKeyInParent);
   }

   public boolean add(CPartCatalogResponse record) {
      return internalAdd(record);
   }

   public void add(int index, CPartCatalogResponse record) {
      internalAdd(index, record);
   }

   public void add(CPartCatalogResponseArray array) {
      internalAdd(array);
   }

   public void assign(CPartCatalogResponseArray from) throws SystemException {
      assign(from, true);
   }

   public boolean contains(CPartCatalogResponse record) {
      return internalContains(record);
   }

   public boolean equals(CPartCatalogResponse record) {
      return internalEquals(record);
   }

   public CPartCatalogResponse firstElement() {
      return (CPartCatalogResponse)internalFirstElement();
   }

   public CPartCatalogResponse get(int index) {
      return (CPartCatalogResponse)internalGet(index);
   }

   public int indexOf(CPartCatalogResponse record) {
      return internalIndexOf(record);
   }

   public CPartCatalogResponse lastElement() {
      return (CPartCatalogResponse)internalLastElement();
   }

   public int lastIndexOf(CPartCatalogResponse record) {
      return internalLastIndexOf(record);
   }

   public CPartCatalogResponse remove(int index) {
      return (CPartCatalogResponse)internalRemove(index);
   }

   public CPartCatalogResponse set(int index, CPartCatalogResponse record) {
      return (CPartCatalogResponse)internalSet(index, record);
   }

   public FndAbstractRecord newRecord() {
      return new CPartCatalogResponse();
   }

   protected FndAbstractRecord newRecord(FndTokenReader stream) throws ParseException {
      CPartCatalogResponse record = new CPartCatalogResponse();
      record.parse(stream);
      return record;
   } 

   protected FndAttribute newAttribute(FndAttributeMeta meta) {
       return new CPartCatalogResponseArray(meta);
   }
}
