/*
* ==================================================================================
* File:             CPartCatalogServiceBean.java
* Software Package: CPartCatalogServiceGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cpartcatalogservicegroup;

import ifs.application.cpartcatalogservicegroup.impl.CPartCatalogServiceImpl;
import ifs.fnd.record.*;
import ifs.fnd.sf.j2ee.*;
import ifs.fnd.base.*;
import ifs.fnd.sf.*;
import javax.ejb.*;

public class CPartCatalogServiceBean extends FndImplementationBean {
   private CPartCatalogServiceImpl implementation;

   public void ejbCreate() throws CreateException {
      super.ejbCreate();
      implementation = new CPartCatalogServiceWrapper();
   }

   public CPartCatalogResponseArray cCreatePartCatalog(CPartCatalogRequestArray partCatalogRequest) throws IfsException {
      try {
         beforeCall();
         return implementation.cCreatePartCatalog(partCatalogRequest);
      }
      catch (IfsException e) {
         rollback();
         throw e;
      }
      finally {
         afterCall();
      }
   }

}