/*
* ==================================================================================
* File:             ChangePrStatusInputArray.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import ifs.fnd.record.*;
import ifs.fnd.record.serialization.*;
import ifs.fnd.base.*;

/** 
 * Array of <code>ChangePrStatusInput</code>.
 */
public class ChangePrStatusInputArray extends FndAbstractArray {

   public ChangePrStatusInputArray() {
      super();
   }

   public ChangePrStatusInputArray(FndAttributeMeta meta) {
      super(meta);
   }

   public ChangePrStatusInputArray(FndAttributeMeta meta, FndCompoundReference parentKeyInParent) {
      super(meta, parentKeyInParent);
   }

   public boolean add(ChangePrStatusInput record) {
      return internalAdd(record);
   }

   public void add(int index, ChangePrStatusInput record) {
      internalAdd(index, record);
   }

   public void add(ChangePrStatusInputArray array) {
      internalAdd(array);
   }

   public void assign(ChangePrStatusInputArray from) throws SystemException {
      assign(from, true);
   }

   public boolean contains(ChangePrStatusInput record) {
      return internalContains(record);
   }

   public boolean equals(ChangePrStatusInput record) {
      return internalEquals(record);
   }

   public ChangePrStatusInput firstElement() {
      return (ChangePrStatusInput)internalFirstElement();
   }

   public ChangePrStatusInput get(int index) {
      return (ChangePrStatusInput)internalGet(index);
   }

   public int indexOf(ChangePrStatusInput record) {
      return internalIndexOf(record);
   }

   public ChangePrStatusInput lastElement() {
      return (ChangePrStatusInput)internalLastElement();
   }

   public int lastIndexOf(ChangePrStatusInput record) {
      return internalLastIndexOf(record);
   }

   public ChangePrStatusInput remove(int index) {
      return (ChangePrStatusInput)internalRemove(index);
   }

   public ChangePrStatusInput set(int index, ChangePrStatusInput record) {
      return (ChangePrStatusInput)internalSet(index, record);
   }

   public FndAbstractRecord newRecord() {
      return new ChangePrStatusInput();
   }

   protected FndAbstractRecord newRecord(FndTokenReader stream) throws ParseException {
      ChangePrStatusInput record = new ChangePrStatusInput();
      record.parse(stream);
      return record;
   } 

   protected FndAttribute newAttribute(FndAttributeMeta meta) {
       return new ChangePrStatusInputArray(meta);
   }
}
