/*
* ==================================================================================
* File:             ChangePrStatusReturnMessage.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import ifs.fnd.record.*;
import ifs.fnd.base.*;

/**
 * This view represents the <code>ChangePrStatusReturnMessage</code> entity.
 */
public class ChangePrStatusReturnMessage extends FndView {

   public static final FndRecordMeta viewMeta  = new FndRecordMeta("CSHOPORDERSERVICESGROUP", "CHANGE_PR_STATUS_RETURN_MESSAGE").setViewClassName("ifs.application.cshoporderservicesgroup.ChangePrStatusReturnMessage");

   /**
    * StatusCode
    */
   public final FndText      statusCode    = new FndText(Meta.statusCode);
   /**
    * ReturnMessage
    */
   public final FndText      returnMessage = new FndText(Meta.returnMessage);
   /**
    * RequisitionNo
    */
   public final FndText      requisitionNo = new FndText(Meta.requisitionNo);

   public ChangePrStatusReturnMessage() {
      this(viewMeta);
   }

   protected ChangePrStatusReturnMessage(FndRecordMeta meta) {
      super(meta);
      add(statusCode);
      add(returnMessage);
      add(requisitionNo);
   }

   public void assign(ChangePrStatusReturnMessage from) throws SystemException {
      super.assign(from);
   }

   public FndAbstractRecord newInstance() {
      return new ChangePrStatusReturnMessage();
   }

   public FndAbstractArray newArrayInstance() {
      return new ChangePrStatusReturnMessageArray();
   }

   public void transformTo(final ChangePrStatusReturnMessage to) throws SystemException {
      transformView(to);
   }

   public static class Meta {
      public static final FndAttributeMeta statusCode      = new FndAttributeMeta(viewMeta, "STATUS_CODE", "", 0, 50);
      public static final FndAttributeMeta returnMessage   = new FndAttributeMeta(viewMeta, "RETURN_MESSAGE", "", 0, 2000);
      public static final FndAttributeMeta requisitionNo   = new FndAttributeMeta(viewMeta, "REQUISITION_NO", "", 0, 20);
   }
}
