/*
* ==================================================================================
* File:             ChangePrStatusInput.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import ifs.fnd.record.*;
import ifs.fnd.base.*;

/**
 * This view represents the <code>ChangePrStatusInput</code> entity.
 */
public class ChangePrStatusInput extends FndView {

   public static final FndRecordMeta viewMeta  = new FndRecordMeta("CSHOPORDERSERVICESGROUP", "CHANGE_PR_STATUS_INPUT").setViewClassName("ifs.application.cshoporderservicesgroup.ChangePrStatusInput");

   /**
    * RequisitionNo
    */
   public final FndText      requisitionNo = new FndText(Meta.requisitionNo);
   /**
    * Action
    */
   public final FndText      action        = new FndText(Meta.action);

   public ChangePrStatusInput() {
      this(viewMeta);
   }

   protected ChangePrStatusInput(FndRecordMeta meta) {
      super(meta);
      add(requisitionNo);
      add(action);
   }

   public void assign(ChangePrStatusInput from) throws SystemException {
      super.assign(from);
   }

   public FndAbstractRecord newInstance() {
      return new ChangePrStatusInput();
   }

   public FndAbstractArray newArrayInstance() {
      return new ChangePrStatusInputArray();
   }

   public void transformTo(final ChangePrStatusInput to) throws SystemException {
      transformView(to);
   }

   public static class Meta {
      public static final FndAttributeMeta requisitionNo   = new FndAttributeMeta(viewMeta, "REQUISITION_NO", "", 0, 20);
      public static final FndAttributeMeta action          = new FndAttributeMeta(viewMeta, "ACTION", "", 0, 20);
   }
}
