/*
* ==================================================================================
* File:             CShopOrdPlsqlHandlerFactory.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import ifs.fnd.base.*;
import ifs.fnd.sf.j2ee.*;

public class CShopOrdPlsqlHandlerFactory {
   private static final String jndiName = "CShopOrdPlsqlHandler";
   /**
    * Get an instance of a <code>[CShopOrdPlsqlHandler]</code>.
    * @return An instance of a <code>[CShopOrdPlsqlHandler]</code>.
    * @throws SystemException If there is a serious problem locating the handler. May indicate a deployment error.
    */
   public static CShopOrdPlsqlHandler getHandler() throws SystemException {
      FndServiceLocator serviceLocator = FndServiceLocator.getInstance();
      try {
         CShopOrdPlsqlHandlerHome home = (CShopOrdPlsqlHandlerHome) serviceLocator.getLocalHome(jndiName);
         return home.create();
      }
      catch (SystemException e) {
         serviceLocator.invalidateCachedHome(jndiName);
         throw e;
      }
      catch (Exception e) {
         serviceLocator.invalidateCachedHome(jndiName);
         throw new SystemException(e, "EJB_CREATE_ERROR: Unable to create &1. Reason: &2", jndiName, e.toString());
      }
   }
}
