/*
* ==================================================================================
* File:             CShopOrderServicesImplBase.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.sf.*;
import ifs.fnd.sf.storage.*;
import ifs.fnd.record.*;
import ifs.fnd.sf.storage.FndAbstractHandler;

/**
 * Base implementation of the <code>CShopOrderServices</code> handler.
 */
public abstract class CShopOrderServicesImplBase extends FndAbstractHandler implements CShopOrderServices.Operations {

   /**
    * <p><b>Remarks:</b>
    * @param ChangePrStatusInput ChangePrStatusInput
    * @return ChangePrStatusReturnMessage
    * @throws IfsException
    */
   public abstract ChangePrStatusReturnMessage cChangePrStatus(ChangePrStatusInput changePrStatusInput) throws IfsException;

   /**
    * <p><b>Remarks:</b>
    * @param ShopOrd ShopOrd
    * @return ShopOrd
    * @throws IfsException
    */
   public abstract ShopOrd cGetShopOrderRequest(ShopOrd shopOrd) throws IfsException;

   /**
    * <p><b>Remarks:</b>
    * @param ShopOrd ShopOrd
    * @return ShopOrd
    * @throws IfsException
    */
   public abstract ShopOrd cQueryShopOrderRequest(ShopOrd shopOrd) throws IfsException;

   /**
    * <p><b>Remarks:</b>
    * @param ShopOrd ShopOrd
    * @return void
    * @throws IfsException
    */
   public abstract void cReceiveShopOrder(ShopOrd shopOrd) throws IfsException;

   /**
    * <p><b>Remarks:</b>
    * @param ShopOrd ShopOrd
    * @return ShopOrd
    * @throws IfsException
    */
   public abstract ShopOrd cSendShopOrder(ShopOrd shopOrd) throws IfsException;
}
