/*
* ==================================================================================
* File:             CShopOrdPlsqlHandler.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import java.util.Date;
import ifs.fnd.base.*;
import ifs.fnd.record.*;
import javax.ejb.EJBLocalObject;

/**
 * Interface for the <code>CShopOrdPlsqlHandler</code> handler.
 */
public interface CShopOrdPlsqlHandler extends EJBLocalObject {
   /**
    * <p><b>Remarks:</b>
    * @param String RequisitionNo
    * @param String Action
    * @return void
    * @throws IfsException
    */
   public void changePrStatus(String requisitionNo, String action) throws IfsException;

   public interface Operations   {

      /**
       * <p><b>Remarks:</b>
       * @param String RequisitionNo
       * @param String Action
       * @return void
       * @throws IfsException
       */
      public void changePrStatus(String requisitionNo, String action) throws IfsException;
   }
}