/*
* ==================================================================================
* File:             CShopOrdPlsqlHandlerHome.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/


package ifs.application.cshoporderservicesgroup;

import javax.ejb.EJBLocalHome;
import javax.ejb.CreateException;

/**
 * Home interface for the <code>CShopOrdPlsqlHandler</code> handler
*/
public interface CShopOrdPlsqlHandlerHome extends EJBLocalHome {
   CShopOrdPlsqlHandler create() throws CreateException;
}