/*
* ==================================================================================
* File:             CShopOrderServicesHome.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/


package ifs.application.cshoporderservicesgroup;

import javax.ejb.EJBLocalHome;
import javax.ejb.CreateException;

/**
 * Home interface for the <code>CShopOrderServices</code> handler
*/
public interface CShopOrderServicesHome extends EJBLocalHome {
   CShopOrderServices create() throws CreateException;
}