/*
* ==================================================================================
* File:             ShopOrd.java
* Software Package: CShopOrderServicesGroup
*
* DO NOT EDIT this file. It was generated and will be overwritten at next generation
*
* ==================================================================================
*/

package ifs.application.cshoporderservicesgroup;

import ifs.fnd.record.*;
import ifs.fnd.base.*;

/**
 * This view represents the <code>ShopOrd</code> entity.
 */
public class ShopOrd extends FndLUWrapperView {

   public static final FndRecordMeta viewMeta  = new FndRecordMeta("", "CSHOPORDERSERVICESGROUP", "SHOP_ORD", "SHOP_ORD", "ShopOrd", "SHOP_ORD_API").setViewClassName("ifs.application.cshoporderservicesgroup.ShopOrd");

   /**
    * OrderNo
    */
   public final FndText      orderNo                  = new FndText(Meta.orderNo);
   /**
    * ReleaseNo
    */
   public final FndText      releaseNo                = new FndText(Meta.releaseNo);
   /**
    * SequenceNo
    */
   public final FndText      sequenceNo               = new FndText(Meta.sequenceNo);
   /**
    * OrderCode
    */
   public final FndText      orderCode                = new FndText(Meta.orderCode);
   /**
    * OrderCodeDb
    */
   public final FndText      orderCodeDb              = new FndText(Meta.orderCodeDb);
   /**
    * Contract
    */
   public final FndText      contract                 = new FndText(Meta.contract);
   /**
    * PartNo
    */
   public final FndText      partNo                   = new FndText(Meta.partNo);
   /**
    * EngChgLevel
    */
   public final FndText      engChgLevel              = new FndText(Meta.engChgLevel);
   /**
    * LotBatchNo
    */
   public final FndText      lotBatchNo               = new FndText(Meta.lotBatchNo);
   /**
    * StructureAlternative
    */
   public final FndText      structureAlternative     = new FndText(Meta.structureAlternative);
   /**
    * RoutingRevision
    */
   public final FndText      routingRevision          = new FndText(Meta.routingRevision);
   /**
    * RoutingAlternative
    */
   public final FndText      routingAlternative       = new FndText(Meta.routingAlternative);
   /**
    * SerialBegin
    */
   public final FndText      serialBegin              = new FndText(Meta.serialBegin);
   /**
    * SerialEnd
    */
   public final FndText      serialEnd                = new FndText(Meta.serialEnd);
   /**
    * ShopOrdRoutSerial
    */
   public final FndText      shopOrdRoutSerial        = new FndText(Meta.shopOrdRoutSerial);
   /**
    * OrgStartDate
    */
   public final FndTimestamp orgStartDate             = new FndTimestamp(Meta.orgStartDate);
   /**
    * OrgDueDate
    */
   public final FndTimestamp orgDueDate               = new FndTimestamp(Meta.orgDueDate);
   /**
    * RevisedStartDate
    */
   public final FndTimestamp revisedStartDate         = new FndTimestamp(Meta.revisedStartDate);
   /**
    * RevisedDueDate
    */
   public final FndTimestamp revisedDueDate           = new FndTimestamp(Meta.revisedDueDate);
   /**
    * NeedDate
    */
   public final FndTimestamp needDate                 = new FndTimestamp(Meta.needDate);
   /**
    * EarliestStartDate
    */
   public final FndTimestamp earliestStartDate        = new FndTimestamp(Meta.earliestStartDate);
   /**
    * CompleteDate
    */
   public final FndTimestamp completeDate             = new FndTimestamp(Meta.completeDate);
   /**
    * CloseDate
    */
   public final FndTimestamp closeDate                = new FndTimestamp(Meta.closeDate);
   /**
    * CloseTolerance
    */
   public final FndNumber    closeTolerance           = new FndNumber(Meta.closeTolerance);
   /**
    * OrgQtyDue
    */
   public final FndNumber    orgQtyDue                = new FndNumber(Meta.orgQtyDue);
   /**
    * RevisedQtyDue
    */
   public final FndNumber    revisedQtyDue            = new FndNumber(Meta.revisedQtyDue);
   /**
    * QtyOnOrder
    */
   public final FndNumber    qtyOnOrder               = new FndNumber(Meta.qtyOnOrder);
   /**
    * QtyReleased
    */
   public final FndNumber    qtyReleased              = new FndNumber(Meta.qtyReleased);
   /**
    * QtyComplete
    */
   public final FndNumber    qtyComplete              = new FndNumber(Meta.qtyComplete);
   /**
    * QtyQa
    */
   public final FndNumber    qtyQa                    = new FndNumber(Meta.qtyQa);
   /**
    * QtyRejected
    */
   public final FndNumber    qtyRejected              = new FndNumber(Meta.qtyRejected);
   /**
    * QaScrapped
    */
   public final FndNumber    qaScrapped               = new FndNumber(Meta.qaScrapped);
   /**
    * QtyDiff
    */
   public final FndNumber    qtyDiff                  = new FndNumber(Meta.qtyDiff);
   /**
    * OperationScrapped
    */
   public final FndNumber    operationScrapped        = new FndNumber(Meta.operationScrapped);
   /**
    * DemandCode
    */
   public final FndText      demandCode               = new FndText(Meta.demandCode);
   /**
    * DemandCodeDb
    */
   public final FndText      demandCodeDb             = new FndText(Meta.demandCodeDb);
   /**
    * CloseCode
    */
   public final FndText      closeCode                = new FndText(Meta.closeCode);
   /**
    * CloseCodeDb
    */
   public final FndText      closeCodeDb              = new FndText(Meta.closeCodeDb);
   /**
    * PartialDirection
    */
   public final FndText      partialDirection         = new FndText(Meta.partialDirection);
   /**
    * PartialOperation
    */
   public final FndText      partialOperation         = new FndText(Meta.partialOperation);
   /**
    * SchedDirection
    */
   public final FndText      schedDirection           = new FndText(Meta.schedDirection);
   /**
    * SchedDirectionDb
    */
   public final FndText      schedDirectionDb         = new FndText(Meta.schedDirectionDb);
   /**
    * SchedCapacity
    */
   public final FndText      schedCapacity            = new FndText(Meta.schedCapacity);
   /**
    * SchedCapacityDb
    */
   public final FndText      schedCapacityDb          = new FndText(Meta.schedCapacityDb);
   /**
    * ReschedFlag
    */
   public final FndText      reschedFlag              = new FndText(Meta.reschedFlag);
   /**
    * ReschedFlagDb
    */
   public final FndText      reschedFlagDb            = new FndText(Meta.reschedFlagDb);
   /**
    * ReschedCode
    */
   public final FndText      reschedCode              = new FndText(Meta.reschedCode);
   /**
    * ReschedCodeDb
    */
   public final FndText      reschedCodeDb            = new FndText(Meta.reschedCodeDb);
   /**
    * PriorityNo
    */
   public final FndNumber    priorityNo               = new FndNumber(Meta.priorityNo);
   /**
    * SecurityClass
    */
   public final FndText      securityClass            = new FndText(Meta.securityClass);
   /**
    * Source
    */
   public final FndText      source                   = new FndText(Meta.source);
   /**
    * AssignFlag
    */
   public final FndText      assignFlag               = new FndText(Meta.assignFlag);
   /**
    * AssignFlagDb
    */
   public final FndText      assignFlagDb             = new FndText(Meta.assignFlagDb);
   /**
    * PickList
    */
   public final FndText      pickList                 = new FndText(Meta.pickList);
   /**
    * PickListDb
    */
   public final FndText      pickListDb               = new FndText(Meta.pickListDb);
   /**
    * PreAccountingId
    */
   public final FndNumber    preAccountingId          = new FndNumber(Meta.preAccountingId);
   /**
    * RejectReason
    */
   public final FndText      rejectReason             = new FndText(Meta.rejectReason);
   /**
    * ProposedLocation
    */
   public final FndText      proposedLocation         = new FndText(Meta.proposedLocation);
   /**
    * WorkInstruct
    */
   public final FndText      workInstruct             = new FndText(Meta.workInstruct);
   /**
    * WorkInstructDb
    */
   public final FndText      workInstructDb           = new FndText(Meta.workInstructDb);
   /**
    * NoteId
    */
   public final FndNumber    noteId                   = new FndNumber(Meta.noteId);
   /**
    * NoteText
    */
   public final FndText      noteText                 = new FndText(Meta.noteText);
   /**
    * DateEntered
    */
   public final FndTimestamp dateEntered              = new FndTimestamp(Meta.dateEntered);
   /**
    * LastActivityDate
    */
   public final FndTimestamp lastActivityDate         = new FndTimestamp(Meta.lastActivityDate);
   /**
    * ProcessType
    */
   public final FndText      processType              = new FndText(Meta.processType);
   /**
    * CustomerOrderNo
    */
   public final FndText      customerOrderNo          = new FndText(Meta.customerOrderNo);
   /**
    * CustomerLineNo
    */
   public final FndText      customerLineNo           = new FndText(Meta.customerLineNo);
   /**
    * CustomerRelNo
    */
   public final FndText      customerRelNo            = new FndText(Meta.customerRelNo);
   /**
    * CustomerLineItemNo
    */
   public final FndNumber    customerLineItemNo       = new FndNumber(Meta.customerLineItemNo);
   /**
    * CustomerNo
    */
   public final FndText      customerNo               = new FndText(Meta.customerNo);
   /**
    * ProjectId
    */
   public final FndText      projectId                = new FndText(Meta.projectId);
   /**
    * ActivitySeq
    */
   public final FndNumber    activitySeq              = new FndNumber(Meta.activitySeq);
   /**
    * PriorityCategory
    */
   public final FndText      priorityCategory         = new FndText(Meta.priorityCategory);
   /**
    * SourceOrderNo
    */
   public final FndText      sourceOrderNo            = new FndText(Meta.sourceOrderNo);
   /**
    * SourceReleaseNo
    */
   public final FndText      sourceReleaseNo          = new FndText(Meta.sourceReleaseNo);
   /**
    * SourceSequenceNo
    */
   public final FndText      sourceSequenceNo         = new FndText(Meta.sourceSequenceNo);
   /**
    * SplitReason
    */
   public final FndText      splitReason              = new FndText(Meta.splitReason);
   /**
    * MrbNumber
    */
   public final FndText      mrbNumber                = new FndText(Meta.mrbNumber);
   /**
    * PicklistType
    */
   public final FndText      picklistType             = new FndText(Meta.picklistType);
   /**
    * PicklistTypeDb
    */
   public final FndText      picklistTypeDb           = new FndText(Meta.picklistTypeDb);
   /**
    * ConfigurationId
    */
   public final FndText      configurationId          = new FndText(Meta.configurationId);
   /**
    * BalancedCostDiff
    */
   public final FndNumber    balancedCostDiff         = new FndNumber(Meta.balancedCostDiff);
   /**
    * JobId
    */
   public final FndText      jobId                    = new FndText(Meta.jobId);
   /**
    * ConditionCode
    */
   public final FndText      conditionCode            = new FndText(Meta.conditionCode);
   /**
    * LotBatchString
    */
   public final FndText      lotBatchString           = new FndText(Meta.lotBatchString);
   /**
    * MaintLevelStruct
    */
   public final FndText      maintLevelStruct         = new FndText(Meta.maintLevelStruct);
   /**
    * MaintLevelRout
    */
   public final FndText      maintLevelRout           = new FndText(Meta.maintLevelRout);
   /**
    * PartOwnership
    */
   public final FndText      partOwnership            = new FndText(Meta.partOwnership);
   /**
    * PartOwnershipDb
    */
   public final FndText      partOwnershipDb          = new FndText(Meta.partOwnershipDb);
   /**
    * OwningCustomerNo
    */
   public final FndText      owningCustomerNo         = new FndText(Meta.owningCustomerNo);
   /**
    * MroVisitId
    */
   public final FndNumber    mroVisitId               = new FndNumber(Meta.mroVisitId);
   /**
    * MroIntOrdHeader
    */
   public final FndText      mroIntOrdHeader          = new FndText(Meta.mroIntOrdHeader);
   /**
    * MroIntOrder
    */
   public final FndText      mroIntOrder              = new FndText(Meta.mroIntOrder);
   /**
    * DispoOrderNo
    */
   public final FndText      dispoOrderNo             = new FndText(Meta.dispoOrderNo);
   /**
    * DispoReleaseNo
    */
   public final FndText      dispoReleaseNo           = new FndText(Meta.dispoReleaseNo);
   /**
    * DispoSequenceNo
    */
   public final FndText      dispoSequenceNo          = new FndText(Meta.dispoSequenceNo);
   /**
    * DispoLineItem
    */
   public final FndNumber    dispoLineItem            = new FndNumber(Meta.dispoLineItem);
   /**
    * ModsDefined
    */
   public final FndText      modsDefined              = new FndText(Meta.modsDefined);
   /**
    * ModsDefinedDb
    */
   public final FndText      modsDefinedDb            = new FndText(Meta.modsDefinedDb);
   /**
    * RepairsDefined
    */
   public final FndText      repairsDefined           = new FndText(Meta.repairsDefined);
   /**
    * RepairsDefinedDb
    */
   public final FndText      repairsDefinedDb         = new FndText(Meta.repairsDefinedDb);
   /**
    * PartialPartRequired
    */
   public final FndText      partialPartRequired      = new FndText(Meta.partialPartRequired);
   /**
    * ReplicateChanges
    */
   public final FndText      replicateChanges         = new FndText(Meta.replicateChanges);
   /**
    * AlternateComponentUsed
    */
   public final FndText      alternateComponentUsed   = new FndText(Meta.alternateComponentUsed);
   /**
    * AlternateComponentUsedDb
    */
   public final FndText      alternateComponentUsedDb = new FndText(Meta.alternateComponentUsedDb);
   /**
    * UseCostDistribution
    */
   public final FndText      useCostDistribution      = new FndText(Meta.useCostDistribution);
   /**
    * UseCostDistributionDb
    */
   public final FndText      useCostDistributionDb    = new FndText(Meta.useCostDistributionDb);
   /**
    * ClosedInCbs
    */
   public final FndText      closedInCbs              = new FndText(Meta.closedInCbs);
   /**
    * ClosedInCbsDb
    */
   public final FndText      closedInCbsDb            = new FndText(Meta.closedInCbsDb);
   /**
    * CaseId
    */
   public final FndNumber    caseId                   = new FndNumber(Meta.caseId);
   /**
    * TaskId
    */
   public final FndNumber    taskId                   = new FndNumber(Meta.taskId);
   /**
    * LastAvailRunDate
    */
   public final FndTimestamp lastAvailRunDate         = new FndTimestamp(Meta.lastAvailRunDate);
   /**
    * CroNo
    */
   public final FndNumber    croNo                    = new FndNumber(Meta.croNo);
   /**
    * CroLine
    */
   public final FndNumber    croLine                  = new FndNumber(Meta.croLine);
   /**
    * EsoSupplier
    */
   public final FndText      esoSupplier              = new FndText(Meta.esoSupplier);
   /**
    * EsoServiceType
    */
   public final FndText      esoServiceType           = new FndText(Meta.esoServiceType);
   /**
    * ShrinkageFactor
    */
   public final FndNumber    shrinkageFactor          = new FndNumber(Meta.shrinkageFactor);
   /**
    * PlannedOpScrap
    */
   public final FndNumber    plannedOpScrap           = new FndNumber(Meta.plannedOpScrap);
   /**
    * Objstate
    */
   public final FndText      objstate                 = new FndText(Meta.objstate);
   /**
    * Objevents
    */
   public final FndText      objevents                = new FndText(Meta.objevents);
   /**
    * State
    */
   public final FndText      state                    = new FndText(Meta.state);

   public final Reference  primaryKey = new Reference(Meta.primaryKey, orderNo, releaseNo, sequenceNo);

   public ShopOrd() {
      this(viewMeta);
   }

   protected ShopOrd(FndRecordMeta meta) {
      super(meta);
      add(orderNo);
      add(releaseNo);
      add(sequenceNo);
      add(orderCode);
      add(orderCodeDb);
      add(contract);
      add(partNo);
      add(engChgLevel);
      add(lotBatchNo);
      add(structureAlternative);
      add(routingRevision);
      add(routingAlternative);
      add(serialBegin);
      add(serialEnd);
      add(shopOrdRoutSerial);
      add(orgStartDate);
      add(orgDueDate);
      add(revisedStartDate);
      add(revisedDueDate);
      add(needDate);
      add(earliestStartDate);
      add(completeDate);
      add(closeDate);
      add(closeTolerance);
      add(orgQtyDue);
      add(revisedQtyDue);
      add(qtyOnOrder);
      add(qtyReleased);
      add(qtyComplete);
      add(qtyQa);
      add(qtyRejected);
      add(qaScrapped);
      add(qtyDiff);
      add(operationScrapped);
      add(demandCode);
      add(demandCodeDb);
      add(closeCode);
      add(closeCodeDb);
      add(partialDirection);
      add(partialOperation);
      add(schedDirection);
      add(schedDirectionDb);
      add(schedCapacity);
      add(schedCapacityDb);
      add(reschedFlag);
      add(reschedFlagDb);
      add(reschedCode);
      add(reschedCodeDb);
      add(priorityNo);
      add(securityClass);
      add(source);
      add(assignFlag);
      add(assignFlagDb);
      add(pickList);
      add(pickListDb);
      add(preAccountingId);
      add(rejectReason);
      add(proposedLocation);
      add(workInstruct);
      add(workInstructDb);
      add(noteId);
      add(noteText);
      add(dateEntered);
      add(lastActivityDate);
      add(processType);
      add(customerOrderNo);
      add(customerLineNo);
      add(customerRelNo);
      add(customerLineItemNo);
      add(customerNo);
      add(projectId);
      add(activitySeq);
      add(priorityCategory);
      add(sourceOrderNo);
      add(sourceReleaseNo);
      add(sourceSequenceNo);
      add(splitReason);
      add(mrbNumber);
      add(picklistType);
      add(picklistTypeDb);
      add(configurationId);
      add(balancedCostDiff);
      add(jobId);
      add(conditionCode);
      add(lotBatchString);
      add(maintLevelStruct);
      add(maintLevelRout);
      add(partOwnership);
      add(partOwnershipDb);
      add(owningCustomerNo);
      add(mroVisitId);
      add(mroIntOrdHeader);
      add(mroIntOrder);
      add(dispoOrderNo);
      add(dispoReleaseNo);
      add(dispoSequenceNo);
      add(dispoLineItem);
      add(modsDefined);
      add(modsDefinedDb);
      add(repairsDefined);
      add(repairsDefinedDb);
      add(partialPartRequired);
      add(replicateChanges);
      add(alternateComponentUsed);
      add(alternateComponentUsedDb);
      add(useCostDistribution);
      add(useCostDistributionDb);
      add(closedInCbs);
      add(closedInCbsDb);
      add(caseId);
      add(taskId);
      add(lastAvailRunDate);
      add(croNo);
      add(croLine);
      add(esoSupplier);
      add(esoServiceType);
      add(shrinkageFactor);
      add(plannedOpScrap);
      add(objstate);
      add(objevents);
      add(state);
      add(primaryKey);
   }

   public void assign(ShopOrd from) throws SystemException {
      super.assign(from);
   }

   public static class Reference extends FndCompoundReference {
      public Reference(FndCompoundReferenceMeta ref, FndText orderNo, FndText releaseNo, FndText sequenceNo) {
         super(ref);
         add(orderNo);
         add(releaseNo);
         add(sequenceNo);
      }

      public void assign(Reference ref) throws IfsException {
         protectedAssign(ref);
      }

      public boolean isEqualTo(Reference ref) {
         return protectedIsEqualTo(ref);
      }
   }

   public FndAbstractRecord newInstance() {
      return new ShopOrd();
   }

   public FndAbstractArray newArrayInstance() {
      return new ShopOrdArray();
   }

   public static class Meta {
      public static final FndAttributeMeta orderNo         = new FndAttributeMeta(viewMeta, "ORDER_NO","ORDER_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 12);
      public static final FndAttributeMeta releaseNo       = new FndAttributeMeta(viewMeta, "RELEASE_NO","RELEASE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta sequenceNo      = new FndAttributeMeta(viewMeta, "SEQUENCE_NO","SEQUENCE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta orderCode       = new FndAttributeMeta(viewMeta, "ORDER_CODE","ORDER_CODE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta orderCodeDb     = new FndAttributeMeta(viewMeta, "ORDER_CODE_DB","ORDER_CODE_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 3);
      public static final FndAttributeMeta contract        = new FndAttributeMeta(viewMeta, "CONTRACT","CONTRACT",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 5);
      public static final FndAttributeMeta partNo          = new FndAttributeMeta(viewMeta, "PART_NO","PART_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 25);
      public static final FndAttributeMeta engChgLevel     = new FndAttributeMeta(viewMeta, "ENG_CHG_LEVEL","ENG_CHG_LEVEL",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 2);
      public static final FndAttributeMeta lotBatchNo      = new FndAttributeMeta(viewMeta, "LOT_BATCH_NO","LOT_BATCH_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta structureAlternative = new FndAttributeMeta(viewMeta, "STRUCTURE_ALTERNATIVE","STRUCTURE_ALTERNATIVE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta routingRevision = new FndAttributeMeta(viewMeta, "ROUTING_REVISION","ROUTING_REVISION",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta routingAlternative = new FndAttributeMeta(viewMeta, "ROUTING_ALTERNATIVE","ROUTING_ALTERNATIVE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta serialBegin     = new FndAttributeMeta(viewMeta, "SERIAL_BEGIN","SERIAL_BEGIN",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 50);
      public static final FndAttributeMeta serialEnd       = new FndAttributeMeta(viewMeta, "SERIAL_END","SERIAL_END",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 50);
      public static final FndAttributeMeta shopOrdRoutSerial = new FndAttributeMeta(viewMeta, "SHOP_ORD_ROUT_SERIAL","SHOP_ORD_ROUT_SERIAL",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 50);
      public static final FndAttributeMeta orgStartDate    = new FndAttributeMeta(viewMeta, "ORG_START_DATE","ORG_START_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta orgDueDate      = new FndAttributeMeta(viewMeta, "ORG_DUE_DATE","ORG_DUE_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta revisedStartDate = new FndAttributeMeta(viewMeta, "REVISED_START_DATE","REVISED_START_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta revisedDueDate  = new FndAttributeMeta(viewMeta, "REVISED_DUE_DATE","REVISED_DUE_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta needDate        = new FndAttributeMeta(viewMeta, "NEED_DATE","NEED_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta earliestStartDate = new FndAttributeMeta(viewMeta, "EARLIEST_START_DATE","EARLIEST_START_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta completeDate    = new FndAttributeMeta(viewMeta, "COMPLETE_DATE","COMPLETE_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta closeDate       = new FndAttributeMeta(viewMeta, "CLOSE_DATE","CLOSE_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta closeTolerance  = new FndAttributeMeta(viewMeta, "CLOSE_TOLERANCE","CLOSE_TOLERANCE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 2, 0);
      public static final FndAttributeMeta orgQtyDue       = new FndAttributeMeta(viewMeta, "ORG_QTY_DUE","ORG_QTY_DUE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta revisedQtyDue   = new FndAttributeMeta(viewMeta, "REVISED_QTY_DUE","REVISED_QTY_DUE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qtyOnOrder      = new FndAttributeMeta(viewMeta, "QTY_ON_ORDER","QTY_ON_ORDER",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qtyReleased     = new FndAttributeMeta(viewMeta, "QTY_RELEASED","QTY_RELEASED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qtyComplete     = new FndAttributeMeta(viewMeta, "QTY_COMPLETE","QTY_COMPLETE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qtyQa           = new FndAttributeMeta(viewMeta, "QTY_QA","QTY_QA",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qtyRejected     = new FndAttributeMeta(viewMeta, "QTY_REJECTED","QTY_REJECTED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qaScrapped      = new FndAttributeMeta(viewMeta, "QA_SCRAPPED","QA_SCRAPPED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta qtyDiff         = new FndAttributeMeta(viewMeta, "QTY_DIFF","QTY_DIFF",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta operationScrapped = new FndAttributeMeta(viewMeta, "OPERATION_SCRAPPED","OPERATION_SCRAPPED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta demandCode      = new FndAttributeMeta(viewMeta, "DEMAND_CODE","DEMAND_CODE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta demandCodeDb    = new FndAttributeMeta(viewMeta, "DEMAND_CODE_DB","DEMAND_CODE_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 3);
      public static final FndAttributeMeta closeCode       = new FndAttributeMeta(viewMeta, "CLOSE_CODE","CLOSE_CODE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta closeCodeDb     = new FndAttributeMeta(viewMeta, "CLOSE_CODE_DB","CLOSE_CODE_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta partialDirection = new FndAttributeMeta(viewMeta, "PARTIAL_DIRECTION","PARTIAL_DIRECTION",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta partialOperation = new FndAttributeMeta(viewMeta, "PARTIAL_OPERATION","PARTIAL_OPERATION",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 3);
      public static final FndAttributeMeta schedDirection  = new FndAttributeMeta(viewMeta, "SCHED_DIRECTION","SCHED_DIRECTION",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta schedDirectionDb = new FndAttributeMeta(viewMeta, "SCHED_DIRECTION_DB","SCHED_DIRECTION_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta schedCapacity   = new FndAttributeMeta(viewMeta, "SCHED_CAPACITY","SCHED_CAPACITY",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta schedCapacityDb = new FndAttributeMeta(viewMeta, "SCHED_CAPACITY_DB","SCHED_CAPACITY_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta reschedFlag     = new FndAttributeMeta(viewMeta, "RESCHED_FLAG","RESCHED_FLAG",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta reschedFlagDb   = new FndAttributeMeta(viewMeta, "RESCHED_FLAG_DB","RESCHED_FLAG_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta reschedCode     = new FndAttributeMeta(viewMeta, "RESCHED_CODE","RESCHED_CODE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta reschedCodeDb   = new FndAttributeMeta(viewMeta, "RESCHED_CODE_DB","RESCHED_CODE_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta priorityNo      = new FndAttributeMeta(viewMeta, "PRIORITY_NO","PRIORITY_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 5, 0);
      public static final FndAttributeMeta securityClass   = new FndAttributeMeta(viewMeta, "SECURITY_CLASS","SECURITY_CLASS",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 6);
      public static final FndAttributeMeta source          = new FndAttributeMeta(viewMeta, "SOURCE","SOURCE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 25);
      public static final FndAttributeMeta assignFlag      = new FndAttributeMeta(viewMeta, "ASSIGN_FLAG","ASSIGN_FLAG",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta assignFlagDb    = new FndAttributeMeta(viewMeta, "ASSIGN_FLAG_DB","ASSIGN_FLAG_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta pickList        = new FndAttributeMeta(viewMeta, "PICK_LIST","PICK_LIST",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta pickListDb      = new FndAttributeMeta(viewMeta, "PICK_LIST_DB","PICK_LIST_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta preAccountingId = new FndAttributeMeta(viewMeta, "PRE_ACCOUNTING_ID","PRE_ACCOUNTING_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta rejectReason    = new FndAttributeMeta(viewMeta, "REJECT_REASON","REJECT_REASON",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 8);
      public static final FndAttributeMeta proposedLocation = new FndAttributeMeta(viewMeta, "PROPOSED_LOCATION","PROPOSED_LOCATION",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 35);
      public static final FndAttributeMeta workInstruct    = new FndAttributeMeta(viewMeta, "WORK_INSTRUCT","WORK_INSTRUCT",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta workInstructDb  = new FndAttributeMeta(viewMeta, "WORK_INSTRUCT_DB","WORK_INSTRUCT_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta noteId          = new FndAttributeMeta(viewMeta, "NOTE_ID","NOTE_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10, 0);
      public static final FndAttributeMeta noteText        = new FndAttributeMeta(viewMeta, "NOTE_TEXT","NOTE_TEXT",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 2000);
      public static final FndAttributeMeta dateEntered     = new FndAttributeMeta(viewMeta, "DATE_ENTERED","DATE_ENTERED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta lastActivityDate = new FndAttributeMeta(viewMeta, "LAST_ACTIVITY_DATE","LAST_ACTIVITY_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta processType     = new FndAttributeMeta(viewMeta, "PROCESS_TYPE","PROCESS_TYPE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 6);
      public static final FndAttributeMeta customerOrderNo = new FndAttributeMeta(viewMeta, "CUSTOMER_ORDER_NO","CUSTOMER_ORDER_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 12);
      public static final FndAttributeMeta customerLineNo  = new FndAttributeMeta(viewMeta, "CUSTOMER_LINE_NO","CUSTOMER_LINE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta customerRelNo   = new FndAttributeMeta(viewMeta, "CUSTOMER_REL_NO","CUSTOMER_REL_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta customerLineItemNo = new FndAttributeMeta(viewMeta, "CUSTOMER_LINE_ITEM_NO","CUSTOMER_LINE_ITEM_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta customerNo      = new FndAttributeMeta(viewMeta, "CUSTOMER_NO","CUSTOMER_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta projectId       = new FndAttributeMeta(viewMeta, "PROJECT_ID","PROJECT_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta activitySeq     = new FndAttributeMeta(viewMeta, "ACTIVITY_SEQ","ACTIVITY_SEQ",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta priorityCategory = new FndAttributeMeta(viewMeta, "PRIORITY_CATEGORY","PRIORITY_CATEGORY",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta sourceOrderNo   = new FndAttributeMeta(viewMeta, "SOURCE_ORDER_NO","SOURCE_ORDER_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 12);
      public static final FndAttributeMeta sourceReleaseNo = new FndAttributeMeta(viewMeta, "SOURCE_RELEASE_NO","SOURCE_RELEASE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta sourceSequenceNo = new FndAttributeMeta(viewMeta, "SOURCE_SEQUENCE_NO","SOURCE_SEQUENCE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta splitReason     = new FndAttributeMeta(viewMeta, "SPLIT_REASON","SPLIT_REASON",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta mrbNumber       = new FndAttributeMeta(viewMeta, "MRB_NUMBER","MRB_NUMBER",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta picklistType    = new FndAttributeMeta(viewMeta, "PICKLIST_TYPE","PICKLIST_TYPE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta picklistTypeDb  = new FndAttributeMeta(viewMeta, "PICKLIST_TYPE_DB","PICKLIST_TYPE_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta configurationId = new FndAttributeMeta(viewMeta, "CONFIGURATION_ID","CONFIGURATION_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 50);
      public static final FndAttributeMeta balancedCostDiff = new FndAttributeMeta(viewMeta, "BALANCED_COST_DIFF","BALANCED_COST_DIFF",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta jobId           = new FndAttributeMeta(viewMeta, "JOB_ID","JOB_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta conditionCode   = new FndAttributeMeta(viewMeta, "CONDITION_CODE","CONDITION_CODE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta lotBatchString  = new FndAttributeMeta(viewMeta, "LOT_BATCH_STRING","LOT_BATCH_STRING",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta maintLevelStruct = new FndAttributeMeta(viewMeta, "MAINT_LEVEL_STRUCT","MAINT_LEVEL_STRUCT",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta maintLevelRout  = new FndAttributeMeta(viewMeta, "MAINT_LEVEL_ROUT","MAINT_LEVEL_ROUT",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 10);
      public static final FndAttributeMeta partOwnership   = new FndAttributeMeta(viewMeta, "PART_OWNERSHIP","PART_OWNERSHIP",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta partOwnershipDb = new FndAttributeMeta(viewMeta, "PART_OWNERSHIP_DB","PART_OWNERSHIP_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta owningCustomerNo = new FndAttributeMeta(viewMeta, "OWNING_CUSTOMER_NO","OWNING_CUSTOMER_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta mroVisitId      = new FndAttributeMeta(viewMeta, "MRO_VISIT_ID","MRO_VISIT_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta mroIntOrdHeader = new FndAttributeMeta(viewMeta, "MRO_INT_ORD_HEADER","MRO_INT_ORD_HEADER",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 12);
      public static final FndAttributeMeta mroIntOrder     = new FndAttributeMeta(viewMeta, "MRO_INT_ORDER","MRO_INT_ORDER",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 12);
      public static final FndAttributeMeta dispoOrderNo    = new FndAttributeMeta(viewMeta, "DISPO_ORDER_NO","DISPO_ORDER_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 12);
      public static final FndAttributeMeta dispoReleaseNo  = new FndAttributeMeta(viewMeta, "DISPO_RELEASE_NO","DISPO_RELEASE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta dispoSequenceNo = new FndAttributeMeta(viewMeta, "DISPO_SEQUENCE_NO","DISPO_SEQUENCE_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4);
      public static final FndAttributeMeta dispoLineItem   = new FndAttributeMeta(viewMeta, "DISPO_LINE_ITEM","DISPO_LINE_ITEM",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta modsDefined     = new FndAttributeMeta(viewMeta, "MODS_DEFINED","MODS_DEFINED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta modsDefinedDb   = new FndAttributeMeta(viewMeta, "MODS_DEFINED_DB","MODS_DEFINED_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta repairsDefined  = new FndAttributeMeta(viewMeta, "REPAIRS_DEFINED","REPAIRS_DEFINED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta repairsDefinedDb = new FndAttributeMeta(viewMeta, "REPAIRS_DEFINED_DB","REPAIRS_DEFINED_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta partialPartRequired = new FndAttributeMeta(viewMeta, "PARTIAL_PART_REQUIRED","PARTIAL_PART_REQUIRED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 1);
      public static final FndAttributeMeta replicateChanges = new FndAttributeMeta(viewMeta, "REPLICATE_CHANGES","REPLICATE_CHANGES",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 100);
      public static final FndAttributeMeta alternateComponentUsed = new FndAttributeMeta(viewMeta, "ALTERNATE_COMPONENT_USED","ALTERNATE_COMPONENT_USED",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta alternateComponentUsedDb = new FndAttributeMeta(viewMeta, "ALTERNATE_COMPONENT_USED_DB","ALTERNATE_COMPONENT_USED_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta useCostDistribution = new FndAttributeMeta(viewMeta, "USE_COST_DISTRIBUTION","USE_COST_DISTRIBUTION",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta useCostDistributionDb = new FndAttributeMeta(viewMeta, "USE_COST_DISTRIBUTION_DB","USE_COST_DISTRIBUTION_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta closedInCbs     = new FndAttributeMeta(viewMeta, "CLOSED_IN_CBS","CLOSED_IN_CBS",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 200);
      public static final FndAttributeMeta closedInCbsDb   = new FndAttributeMeta(viewMeta, "CLOSED_IN_CBS_DB","CLOSED_IN_CBS_DB",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta caseId          = new FndAttributeMeta(viewMeta, "CASE_ID","CASE_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta taskId          = new FndAttributeMeta(viewMeta, "TASK_ID","TASK_ID",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta lastAvailRunDate = new FndAttributeMeta(viewMeta, "LAST_AVAIL_RUN_DATE","LAST_AVAIL_RUN_DATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta croNo           = new FndAttributeMeta(viewMeta, "CRO_NO","CRO_NO",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta croLine         = new FndAttributeMeta(viewMeta, "CRO_LINE","CRO_LINE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta esoSupplier     = new FndAttributeMeta(viewMeta, "ESO_SUPPLIER","ESO_SUPPLIER",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta esoServiceType  = new FndAttributeMeta(viewMeta, "ESO_SERVICE_TYPE","ESO_SERVICE_TYPE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 20);
      public static final FndAttributeMeta shrinkageFactor = new FndAttributeMeta(viewMeta, "SHRINKAGE_FACTOR","SHRINKAGE_FACTOR",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta plannedOpScrap  = new FndAttributeMeta(viewMeta, "PLANNED_OP_SCRAP","PLANNED_OP_SCRAP",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT);
      public static final FndAttributeMeta objstate        = new FndAttributeMeta(viewMeta, "OBJSTATE","OBJSTATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 30);
      public static final FndAttributeMeta objevents       = new FndAttributeMeta(viewMeta, "OBJEVENTS","OBJEVENTS",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);
      public static final FndAttributeMeta state           = new FndAttributeMeta(viewMeta, "STATE","STATE",FndAttributeMeta.QUERYABLE|FndAttributeMeta.PERSISTENT, 4000);

      public static final FndCompoundReferenceMeta primaryKey = new FndCompoundReferenceMeta(viewMeta, "SHOP_ORD_KEY", new FndAttributeMeta[] {orderNo, releaseNo, sequenceNo}, viewMeta, true);
   }
}
